### ISSUE TITLE
StoreTest is flaking

### ISSUE THREAD

**Issue by yigit** [friendlyrobotnyc/Core#21]
If you change studio to run the test repeatly until it fails, it eventually fails.

```
java.lang.IllegalStateException: This job has not completed yet

	at kotlinx.coroutines.JobSupport.getCompletionExceptionOrNull(JobSupport.kt:1127)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:53)
	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:72)
	at com.nytimes.android.external.store3.StoreTest.testNoopAndDefault(StoreTest.kt:116)
```

It might be a test issue but #17 and #18 were found this way, need to investigate further.

**Comment by yigit** [comment]
Something weird is happening that i cannot understand yet.

I change the test to be as follows
```
@Test
    fun testNoopAndDefault() = testScope.runBlockingTest {
        println("1")
        val persister = spy(NoopPersister.create<String, BarCode>())
        val simpleStore = TestStoreBuilder.from(
                fetcher = fetcher,
                persister = persister,
                cached = true
        ).build(storeType)
        println("2")
        whenever(fetcher.fetch(barCode))
                .thenReturn(NETWORK)
        println("3")
        var value = try {
            simpleStore.get(barCode).also {
                println("get returned")
            }
        } catch (th : Throwable) {
            println("error")
            th.printStackTrace()
            "foo"
        } finally {
            println("3.5")
        }
      assertThat(value).isEqualTo(NETWORK)
        println("4")
        val jobs = checkNotNull(coroutineContext[Job]).children.filter { it.isActive }.toSet()
        println("jobs: $jobs")
        println("5")
    }
```

And when it fails, i only see 1-2-3 in the output.
It is not about missing output because if I wrap `runTest` in a `try/finally`, i can still see the output from finally attached it.

I have no idea what is going on :man_shrugging:

**Comment by yigit** [comment]
My first suspicion is the NoOpPersister which creates its own scope.
After changing it to receive the scope, this is the output i received from the test:

```
1
2
3
DONE TEST <<< this is when runBlockingTest returns
get returned
3.5
4
jobs: ["coroutine#4":DeferredCoroutine{Active}@9f37e85]
5
```

**Comment by yigit** [comment]
ok seems like the problem is the NoOpPersister's async behavior.
Good news is that, it does not use any of the deferred nor the scope so just simply revmoing the scope from there will fix the issue.
